pipeline:
  test:
    image: python:3.5
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings.test
    commands:
      - pip install -U -r requirements.dev.txt
      - make lint
      - make full-test
    volumes:
      - '/var/lib/drone/cache/pip:/root/.cache/pip'
